# Generated by Django 3.2.16 on 2022-12-03 17:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221202_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
